spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  forward-headers-strategy: framework

logging:
  level:
    root: INFO
    com.task.mcp_server: INFO